Bugfix/client/file-upload
Equipo-de-desarrollo-IF-UDEA/siga pull request #309
Opened 2024-04-17 19:21 UTC by jeronimoloaiza

Bugs relacionados con el componente file-upload que se implementa en vacaciones y comisiones

2024-04-17 20:19 UTC, DavidTorres-sys requested changes

2024-04-17 20:19 UTC, DavidTorres-sys commented on client/src/app/modules/applications/pages/create/components/vacation/vacation.component.ts
> +  consol() {
Eliminar

2024-04-18 20:27 UTC, jeronimoloaiza commented on client/src/app/modules/applications/pages/create/components/vacation/vacation.component.ts
> +  consol() {
Eliminado el consol.log()

2024-04-18 20:28 UTC, DavidTorres-sys approved these changes

2024-04-18 20:28 UTC, merged